### ISSUE TITLE
[DOC] Filtering example

### ISSUE THREAD

**Issue by mapperr** [peaceant/vis-fzf-mru#1]
Hi!

Just a trivial example about filtering the choice list:

```lua
vis.events.subscribe(vis.events.INIT, function()
    plug.plugins.fzfmru.fzfmru_path = 'grep "^'..os.getenv('PWD')..'" | fzf'
end
```
It presents only files that are located in the current directory hierarchy.

If it sounds right to you maybe it can be added to the README.

Anyway, thanks for the plugin! : )

**Comment by peaceant** [comment]
Thank you. I like it. I've added it to the README.
